backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# This line should *not* be indented
publish_mode: editorial_workflow

# This line should *not* be indented
media_folder: "images" # Media files will be stored in the repo under images/uploads

#
#media_library:
#  name: uploadcare
# config:
#   publicKey: 0c47888701bbac7f15f2

collections:
  - name: "Docs" # Used in routes, e.g., /admin/collections/blog
    label: "Docs" # Used in the UI
    folder: "_posts" # The path to the folder where the documents are stored
    media_folder: "../images/{{year}}-{{month}}-{{day}}-{{slug}}" # The path to the folder where the media files are stored
    public_folder: "images/{{year}}-{{month}}-{{day}}-{{slug}}" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Type", name: "type", widget: "hidden", default: "Document" }
      - { label: "Date", name: "date", widget: "date" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - {
          label: "categories",
          name: "categories",
          widget: "select",
          options:
            [
              { value: "arduino", label: "arduino" },
              { value: "blockly", label: "blockly" },
              { value: "hardware", label: "hardware" },
              { value: "misc", label: "misc" },
              { value: "opensensemap", label: "opensensemap" },
              { value: "sensebox-tutorials", label: "sensebox-tutorials" },
              { value: "sensebox-home", label: "sensebox-home" },
            ],
        }
      - {
          label: "Resources",
          name: "resources",
          widget: "list",
          fields:
            [
              { label: "Name", name: "name", widget: "string" },
              { label: "Link", name: "link", widget: "string" },
            ],
        }
      - { label: "Body", name: "body", widget: "markdown" }
